server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;
    location / {
        try_files $uri $uri/ =404;
    }
    location ~ /\. { deny all; }
}
